apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bravado-app-ing
spec:
  rules:
    - host: bravado-prod.local
      http:
        paths:
          - backend:
              serviceName: bravado
              servicePort: 3000
            path: /