apiVersion: batch/v1
kind: Job
metadata:
  name: bravado-db-job
spec:
  template:
    metadata:
      name: bravado-db-job
    spec:
      containers:
        - name: bravado-db-job
          image: docker.io/iamvictorabedi/bravado:latest
          args: ["rake db:create && rake db:migrate"]
          env:
            - name: DATABASE_NAME
              value: "car_market_production"
            - name: DATABASE_URL
              value: "postgres"
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: "db-user"
                  key: "username"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "db-user-pass"
                  key: "password"
            - name: RAILS_APP
              value: "production"
            - name: REDIS_URL
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: "secret-key-base"
                  key: "secret-key-base"
      restartPolicy: Never
